# This file was generated by GoReleaser. DO NOT EDIT.
cask "teleskopio" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "962294691de293f609be7ba370a037b858cd65e1db0903b85da725f0af5de257"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4159d5bd9e7d6e40316ce938c2f5c6428b62f46d3ee5ffbc1ad1e2be840e5357"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a28f9f0b20c77c2c4e6b97bc070e36f3320a4231c9ce98b27aae75e9e6523759"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f01df0fc03e31b505e0b3626a8afc906d6e41d6d3919930f3f8460372683f0b0"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "teleskopio"
  desc "teleskopio is an open-source small and beautiful Web Kubernetes client."
  homepage "https://teleskopio.github.io/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teleskopio"

  # No zap stanza required

  caveats <<~EOS
    teleskopio --config=config.yaml
  EOS
end
