# This file was generated by GoReleaser. DO NOT EDIT.
cask "teleskopio" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "b5c204fdb82db92fa37248ec37058498d267c5f4581b946757cf0cd5cb998788"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36292b42fcb8c96d9812d58443982fc3dbfca8c0a86cea4d7cbeaf9c31651f44"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a90426d7c0021a77664c21475d045016e6d31d8acdcde93e2c2537ea8b4bf18"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d78dc93795ad51deeee18f131e190ef08d3ef6075e3dbf0301e492ae830abea5"
      url "https://github.com/teleskopio/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "teleskopio"
  desc "teleskopio lightweight kubernetes web client."
  homepage "https://teleskopio.github.io/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teleskopio"

  # No zap stanza required

  caveats <<~EOS
    teleskopio --config=config.yaml
  EOS
end
